### ISSUE TITLE
Data race for backend.watch.(*dummy) resulting in negative waitgroup

### ISSUE THREAD

**Issue by quarnster** [limetext/lime#440]
Can catch this locally too via `for i in {1..10}; do go test github.com/limetext/lime/backend/watch; done`
```go
==================
WARNING: DATA RACE
Write by goroutine 57:
github.com/limetext/lime/backend/watch.(*dummy).FileRenamed()
/home/travis/gopath/src/github.com/limetext/lime/backend/watch/watch_test.go:80 +0x5e
github.com/limetext/lime/backend/watch.(*Watcher).apply()
/home/travis/gopath/src/github.com/limetext/lime/backend/watch/watch.go:261 +0x448
github.com/limetext/lime/backend/watch.func·001()
/home/travis/gopath/src/github.com/limetext/lime/backend/watch/watch.go:203 +0x159
github.com/limetext/lime/backend/watch.(*Watcher).Observe()
/home/travis/gopath/src/github.com/limetext/lime/backend/watch/watch.go:235 +0x179
Previous read by goroutine 54:
github.com/limetext/lime/backend/watch.TestRenameEvent()
/home/travis/gopath/src/github.com/limetext/lime/backend/watch/watch_test.go:395 +0x209
testing.tRunner()
/home/travis/.gvm/gos/go1.3.3/src/pkg/testing/testing.go:422 +0x10f
Goroutine 57 (running) created at:
github.com/limetext/lime/backend/watch.TestRenameEvent()
/home/travis/gopath/src/github.com/limetext/lime/backend/watch/watch_test.go:390 +0x16b
testing.tRunner()
/home/travis/.gvm/gos/go1.3.3/src/pkg/testing/testing.go:422 +0x10f
Goroutine 54 (running) created at:
testing.RunTests()
/home/travis/.gvm/gos/go1.3.3/src/pkg/testing/testing.go:504 +0xb46
testing.Main()
/home/travis/.gvm/gos/go1.3.3/src/pkg/testing/testing.go:435 +0xa2
main.main()
github.com/limetext/lime/backend/watch/_test/_testmain.go:77 +0xdc
==================
panic: sync: negative WaitGroup counter
goroutine 72 [running]:
runtime.panic(0x623900, 0xc2080007d0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/runtime/panic.c:279 +0xf5
sync.(*WaitGroup).Add(0xc20803a520, 0xffffffffffffffff)
/home/travis/.gvm/gos/go1.3.3/src/pkg/sync/waitgroup.go:64 +0x110
sync.(*WaitGroup).Done(0xc20803a520)
/home/travis/.gvm/gos/go1.3.3/src/pkg/sync/waitgroup.go:82 +0x3e
github.com/limetext/lime/backend/watch.(*dummy).FileRenamed(0xc20803a500, 0x6d32b0, 0x11)
/home/travis/gopath/src/github.com/limetext/lime/backend/watch/watch_test.go:81 +0x7c
github.com/limetext/lime/backend/watch.(*Watcher).apply(0xc2080185a0, 0x800, 0x6d32b0, 0x11)
/home/travis/gopath/src/github.com/limetext/lime/backend/watch/watch.go:261 +0x449
github.com/limetext/lime/backend/watch.func·001()
/home/travis/gopath/src/github.com/limetext/lime/backend/watch/watch.go:203 +0x15a
github.com/limetext/lime/backend/watch.(*Watcher).Observe(0xc2080185a0)
/home/travis/gopath/src/github.com/limetext/lime/backend/watch/watch.go:235 +0x17a
created by github.com/limetext/lime/backend/watch.TestRenameEvent
/home/travis/gopath/src/github.com/limetext/lime/backend/watch/watch_test.go:390 +0x16b
goroutine 16 [chan receive]:
testing.RunTests(0x7441e8, 0x838660, 0x10, 0x10, 0x4caa01)
/home/travis/.gvm/gos/go1.3.3/src/pkg/testing/testing.go:505 +0xbb8
testing.Main(0x7441e8, 0x838660, 0x10, 0x10, 0x852a00, 0x0, 0x0, 0x852a00, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/testing/testing.go:435 +0xa3
main.main()
github.com/limetext/lime/backend/watch/_test/_testmain.go:77 +0xdd
goroutine 19 [finalizer wait]:
runtime.park(0x413700, 0x84ef10, 0x83bce9)
/home/travis/.gvm/gos/go1.3.3/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x84ef10, 0x83bce9)
/home/travis/.gvm/gos/go1.3.3/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
/home/travis/.gvm/gos/go1.3.3/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
/home/travis/.gvm/gos/go1.3.3/src/pkg/runtime/proc.c:1445
goroutine 24 [syscall]:
syscall.Syscall(0x3, 0x3, 0x0, 0x0, 0xc208004600, 0x0, 0x61f700)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.Close(0x3, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/zsyscall_linux_amd64.go:267 +0x62
github.com/howeyc/fsnotify.(*Watcher).readEvents(0xc208004480)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:212 +0xf0
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:126 +0x372
goroutine 69 [runnable]:
syscall.Syscall(0x52, 0xc2080423c0, 0xc2080423e0, 0x0, 0x0, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.Rename(0x6d3270, 0x13, 0x6d32b0, 0x11, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/zsyscall_linux_amd64.go:901 +0xe5
os.rename(0x6d3270, 0x13, 0x6d32b0, 0x11, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/os/file_posix.go:52 +0x65
os.Rename(0x6d3270, 0x13, 0x6d32b0, 0x11, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/os/file.go:256 +0x65
github.com/limetext/lime/backend/watch.TestRenameEvent(0xc20802a480)
/home/travis/gopath/src/github.com/limetext/lime/backend/watch/watch_test.go:398 +0x2a4
testing.tRunner(0xc20802a480, 0x8387c8)
/home/travis/.gvm/gos/go1.3.3/src/pkg/testing/testing.go:422 +0x110
created by testing.RunTests
/home/travis/.gvm/gos/go1.3.3/src/pkg/testing/testing.go:504 +0xb46
goroutine 25 [chan receive]:
github.com/howeyc/fsnotify.(*Watcher).purgeEvents(0xc208004480)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify.go:21 +0x89
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:127 +0x38a
goroutine 27 [syscall]:
syscall.Syscall(0x3, 0x3, 0x0, 0x0, 0xc208004840, 0x0, 0x61f700)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.Close(0x3, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/zsyscall_linux_amd64.go:267 +0x62
github.com/howeyc/fsnotify.(*Watcher).readEvents(0xc2080046c0)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:212 +0xf0
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:126 +0x372
goroutine 28 [chan receive]:
github.com/howeyc/fsnotify.(*Watcher).purgeEvents(0xc2080046c0)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify.go:21 +0x89
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:127 +0x38a
goroutine 29 [syscall]:
syscall.Syscall(0x3, 0x4, 0x0, 0x0, 0xc2080049c0, 0x0, 0x61f700)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.Close(0x4, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/zsyscall_linux_amd64.go:267 +0x62
github.com/howeyc/fsnotify.(*Watcher).readEvents(0xc208004360)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:212 +0xf0
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:126 +0x372
goroutine 30 [chan receive]:
github.com/howeyc/fsnotify.(*Watcher).purgeEvents(0xc208004360)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify.go:21 +0x89
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:127 +0x38a
goroutine 31 [syscall]:
syscall.Syscall(0x3, 0x5, 0x0, 0x0, 0xc208004ba0, 0x0, 0x61f700)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.Close(0x5, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/zsyscall_linux_amd64.go:267 +0x62
github.com/howeyc/fsnotify.(*Watcher).readEvents(0xc208004a20)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:212 +0xf0
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:126 +0x372
goroutine 32 [chan receive]:
github.com/howeyc/fsnotify.(*Watcher).purgeEvents(0xc208004a20)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify.go:21 +0x89
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:127 +0x38a
goroutine 34 [syscall]:
syscall.Syscall(0x3, 0x3, 0x0, 0x0, 0xc208004d20, 0x0, 0x61f700)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.Close(0x3, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/zsyscall_linux_amd64.go:267 +0x62
github.com/howeyc/fsnotify.(*Watcher).readEvents(0xc208004420)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:212 +0xf0
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:126 +0x372
goroutine 35 [chan receive]:
github.com/howeyc/fsnotify.(*Watcher).purgeEvents(0xc208004420)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify.go:21 +0x89
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:127 +0x38a
goroutine 37 [syscall]:
syscall.Syscall(0x3, 0x3, 0x0, 0x0, 0xc208004fc0, 0x0, 0x61f700)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.Close(0x3, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/zsyscall_linux_amd64.go:267 +0x62
github.com/howeyc/fsnotify.(*Watcher).readEvents(0xc208004e40)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:212 +0xf0
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:126 +0x372
goroutine 38 [chan receive]:
github.com/howeyc/fsnotify.(*Watcher).purgeEvents(0xc208004e40)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify.go:21 +0x89
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:127 +0x38a
goroutine 40 [syscall]:
syscall.Syscall(0x3, 0x3, 0x0, 0x0, 0xc208005200, 0x0, 0x61f700)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.Close(0x3, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/zsyscall_linux_amd64.go:267 +0x62
github.com/howeyc/fsnotify.(*Watcher).readEvents(0xc208005080)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:212 +0xf0
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:126 +0x372
goroutine 41 [chan receive]:
github.com/howeyc/fsnotify.(*Watcher).purgeEvents(0xc208005080)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify.go:21 +0x89
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:127 +0x38a
goroutine 43 [syscall]:
syscall.Syscall(0x3, 0x3, 0x0, 0x0, 0xc208005440, 0x0, 0x61f700)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.Close(0x3, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/zsyscall_linux_amd64.go:267 +0x62
github.com/howeyc/fsnotify.(*Watcher).readEvents(0xc2080052c0)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:212 +0xf0
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:126 +0x372
goroutine 44 [chan receive]:
github.com/howeyc/fsnotify.(*Watcher).purgeEvents(0xc2080052c0)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify.go:21 +0x89
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:127 +0x38a
goroutine 46 [syscall]:
syscall.Syscall(0x3, 0x3, 0x0, 0x0, 0xc2080054a0, 0x0, 0x61f700)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.Close(0x3, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/zsyscall_linux_amd64.go:267 +0x62
github.com/howeyc/fsnotify.(*Watcher).readEvents(0xc2080042a0)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:212 +0xf0
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:126 +0x372
goroutine 47 [chan receive]:
github.com/howeyc/fsnotify.(*Watcher).purgeEvents(0xc2080042a0)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify.go:21 +0x89
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:127 +0x38a
goroutine 49 [syscall]:
syscall.Syscall(0x3, 0x3, 0x0, 0x0, 0xc208005740, 0x0, 0x61f700)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.Close(0x3, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/zsyscall_linux_amd64.go:267 +0x62
github.com/howeyc/fsnotify.(*Watcher).readEvents(0xc2080055c0)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:212 +0xf0
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:126 +0x372
goroutine 50 [chan receive]:
github.com/howeyc/fsnotify.(*Watcher).purgeEvents(0xc2080055c0)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify.go:21 +0x89
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:127 +0x38a
goroutine 52 [syscall]:
syscall.Syscall(0x3, 0x3, 0x0, 0x0, 0xc208005980, 0x0, 0x61f700)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.Close(0x3, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/zsyscall_linux_amd64.go:267 +0x62
github.com/howeyc/fsnotify.(*Watcher).readEvents(0xc208005800)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:212 +0xf0
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:126 +0x372
goroutine 53 [chan receive]:
github.com/howeyc/fsnotify.(*Watcher).purgeEvents(0xc208005800)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify.go:21 +0x89
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:127 +0x38a
goroutine 55 [syscall]:
syscall.Syscall(0x3, 0x3, 0x0, 0x0, 0xc208005c20, 0x0, 0x61f700)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.Close(0x3, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/zsyscall_linux_amd64.go:267 +0x62
github.com/howeyc/fsnotify.(*Watcher).readEvents(0xc208005aa0)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:212 +0xf0
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:126 +0x372
goroutine 56 [chan receive]:
github.com/howeyc/fsnotify.(*Watcher).purgeEvents(0xc208005aa0)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify.go:21 +0x89
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:127 +0x38a
goroutine 58 [runnable]:
syscall.Syscall(0x0, 0x3, 0xc20812e000, 0x10000, 0x10, 0x10000, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x3, 0xc20812e000, 0x10000, 0x10000, 0x0, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/zsyscall_linux_amd64.go:838 +0x83
syscall.Read(0x3, 0xc20812e000, 0x10000, 0x10000, 0xc208074820, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/syscall_unix.go:136 +0x6a
github.com/howeyc/fsnotify.(*Watcher).readEvents(0xc208005ce0)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:219 +0x1cd
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:126 +0x372
goroutine 59 [chan receive]:
github.com/howeyc/fsnotify.(*Watcher).purgeEvents(0xc208005ce0)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify.go:21 +0x89
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:127 +0x38a
goroutine 60 [select]:
github.com/limetext/lime/backend/watch.(*Watcher).Observe(0xc2080186e0)
/home/travis/gopath/src/github.com/limetext/lime/backend/watch/watch.go:195 +0x2f3
created by github.com/limetext/lime/backend/watch.TestObserve
/home/travis/gopath/src/github.com/limetext/lime/backend/watch/watch_test.go:303 +0x1d7
goroutine 62 [runnable]:
syscall.Syscall(0x0, 0x4, 0xc208054000, 0x10000, 0x10, 0x10000, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x4, 0xc208054000, 0x10000, 0x10000, 0x0, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/zsyscall_linux_amd64.go:838 +0x83
syscall.Read(0x4, 0xc208054000, 0x10000, 0x10000, 0xc2080748d0, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/syscall_unix.go:136 +0x6a
github.com/howeyc/fsnotify.(*Watcher).readEvents(0xc208004d80)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:219 +0x1cd
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:126 +0x372
goroutine 63 [chan receive]:
github.com/howeyc/fsnotify.(*Watcher).purgeEvents(0xc208004d80)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify.go:21 +0x89
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:127 +0x38a
goroutine 64 [select]:
github.com/limetext/lime/backend/watch.(*Watcher).Observe(0xc208018370)
/home/travis/gopath/src/github.com/limetext/lime/backend/watch/watch.go:195 +0x2f3
created by github.com/limetext/lime/backend/watch.TestObserveDirectory
/home/travis/gopath/src/github.com/limetext/lime/backend/watch/watch_test.go:323 +0x1f6
goroutine 66 [runnable]:
syscall.Syscall(0x0, 0x5, 0xc2080f6000, 0x10000, 0x10, 0x10000, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x5, 0xc2080f6000, 0x10000, 0x10000, 0x0, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/zsyscall_linux_amd64.go:838 +0x83
syscall.Read(0x5, 0xc2080f6000, 0x10000, 0x10000, 0xc208074980, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/syscall_unix.go:136 +0x6a
github.com/howeyc/fsnotify.(*Watcher).readEvents(0xc208005f80)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:219 +0x1cd
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:126 +0x372
goroutine 67 [chan receive]:
github.com/howeyc/fsnotify.(*Watcher).purgeEvents(0xc208005f80)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify.go:21 +0x89
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:127 +0x38a
goroutine 68 [select]:
github.com/limetext/lime/backend/watch.(*Watcher).Observe(0xc208018460)
/home/travis/gopath/src/github.com/limetext/lime/backend/watch/watch.go:195 +0x2f3
created by github.com/limetext/lime/backend/watch.TestCreateEvent
/home/travis/gopath/src/github.com/limetext/lime/backend/watch/watch_test.go:345 +0x1a1
goroutine 70 [syscall]:
syscall.Syscall(0x0, 0x6, 0xc208106000, 0x10000, 0x4d374a, 0xc208092200, 0xffffffff)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x6, 0xc208106000, 0x10000, 0x10000, 0x0, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/zsyscall_linux_amd64.go:838 +0x83
syscall.Read(0x6, 0xc208106000, 0x10000, 0x10000, 0xc208074a30, 0x0, 0x0)
/home/travis/.gvm/gos/go1.3.3/src/pkg/syscall/syscall_unix.go:136 +0x6a
github.com/howeyc/fsnotify.(*Watcher).readEvents(0xc2080921e0)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:219 +0x1cd
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:126 +0x372
goroutine 71 [chan receive]:
github.com/howeyc/fsnotify.(*Watcher).purgeEvents(0xc2080921e0)
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify.go:21 +0x89
created by github.com/howeyc/fsnotify.NewWatcher
/home/travis/gopath/src/github.com/howeyc/fsnotify/fsnotify_linux.go:127 +0x38a
FAIL github.com/limetext/lime/backend/watch 0.232s
```

**Comment by quarnster** [comment]
I haven't seen this one in a while and I can't reproduce locally neither. @zoli, @erbridge have you seen this one recently? If not, lets close it.

**Comment by erbridge** [comment]
Not seen it for ages.
