### ISSUE TITLE
qml frontend crashes on startup

### ISSUE THREAD

**Issue by pjoe** [limetext/lime#489]
Running with Qt 5.4 i get following crash:
```
[01/23/15 16:51:50] [FNST] Watch(../../packages/Vintageous)
[01/23/15 16:51:50] [DEBG] ../../packages/Vintageous is watched already
[01/23/15 16:51:50] [FNST] ../../packages/User/Preferences.sublime-settings doesn't exist yet
[01/23/15 16:51:50] [INFO] Loaded ../../packages/User/Preferences.sublime-settings
[01/23/15 16:51:50] [FNST] Watch(../../packages/User/Preferences.sublime-settings)
[01/23/15 16:51:50] [FINE] ../../packages/User/Preferences.sublime-settings doesn't exist, Watching parent directory
[01/23/15 16:51:50] [FNST] Watch(../../packages/User)
[01/23/15 16:51:50] [INFO] Python sez: Exception ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
[01/23/15 16:51:50] [INFO] Python sez: Traceback (most recent call last):
[01/23/15 16:51:50] [INFO] Python sez:   File "/usr/lib/python3.4/threading.py", line 1289, in _shutdown
[01/23/15 16:51:50] [INFO] Python sez:     assert tlock.locked()
[01/23/15 16:51:50] [INFO] Python sez: AssertionError: 
[01/23/15 16:51:50] [INFO] Python sez: 
[01/23/15 16:51:50] [INFO] Python sez: 
[01/23/15 16:51:50] [INFO] Python sez: 
panic: pre-allocated buffer size was wrong

goroutine 1 [running, locked to thread]:
gopkg.in/qml%2ev1.typeInfo(0x805240, 0xc208060100, 0xc208060100)
	/home/pelle/go/src/gopkg.in/qml.v1/datatype.go:357 +0x831
gopkg.in/qml%2ev1.wrapGoValue(0xc2081564e0, 0x805240, 0xc208060100, 0x2, 0x0)
	/home/pelle/go/src/gopkg.in/qml.v1/bridge.go:254 +0x4d3
gopkg.in/qml%2ev1.packDataValue(0x805240, 0xc208060100, 0x7fff8a3fc400, 0xc2081564e0, 0xc208060102)
	/home/pelle/go/src/gopkg.in/qml.v1/datatype.go:116 +0x279
gopkg.in/qml%2ev1.hookGoValueCallMethod(0x21b7c20, 0xc20817b810, 0x0, 0x7fff8a3fc400)
	/home/pelle/go/src/gopkg.in/qml.v1/bridge.go:518 +0x4c0
gopkg.in/qml%2ev1._Cfunc_componentCreateWindow(0x23c52f0, 0x0, 0x0)
	/home/pelle/go/src/gopkg.in/qml.v1/:83 +0x44
gopkg.in/qml%2ev1.func·026()
	/home/pelle/go/src/gopkg.in/qml.v1/qml.go:750 +0x56
gopkg.in/qml%2ev1.hookIdleTimer()
	/home/pelle/go/src/gopkg.in/qml.v1/bridge.go:190 +0x60
gopkg.in/qml%2ev1._Cfunc_applicationExec()
	/home/pelle/go/src/gopkg.in/qml.v1/:59 +0x45
gopkg.in/qml%2ev1.Run(0xc20800a3a0, 0x0, 0x0)
	/home/pelle/go/src/gopkg.in/qml.v1/bridge.go:63 +0x204
main.main()
	/home/pelle/go/src/github.com/limetext/lime/frontend/qml/main.go:857 +0x192

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 6 [chan receive]:
github.com/limetext/text.(*SerializedBuffer).worker(0xc2080b2008)
	/home/pelle/go/src/github.com/limetext/text/serialized_buffer.go:40 +0x61
created by github.com/limetext/text.(*SerializedBuffer).init
	/home/pelle/go/src/github.com/limetext/text/serialized_buffer.go:26 +0xd9

goroutine 7 [syscall]:
syscall.Syscall(0x0, 0x3, 0xc2080ebeb8, 0x10000, 0xc208020380, 0x10000, 0x0)
	/usr/lib/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x3, 0xc2080ebeb8, 0x10000, 0x10000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0x3, 0xc2080ebeb8, 0x10000, 0x10000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/syscall/syscall_unix.go:136 +0x58
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc20802c240)
	/home/pelle/go/src/gopkg.in/fsnotify.v1/inotify.go:144 +0x12b
created by gopkg.in/fsnotify%2ev1.NewWatcher
	/home/pelle/go/src/gopkg.in/fsnotify.v1/inotify.go:47 +0x37c

goroutine 8 [chan receive]:
github.com/limetext/lime/backend/log.(*logWriter).handle(0xc20803b080)
	/home/pelle/go/src/github.com/limetext/lime/backend/log/logwriter.go:36 +0x5e
created by github.com/limetext/lime/backend/log.NewLogWriter
	/home/pelle/go/src/github.com/limetext/lime/backend/log/logwriter.go:31 +0xcb

goroutine 9 [chan receive]:
github.com/limetext/lime/backend.(*Editor).inputthread(0xc2080018c0)
	/home/pelle/go/src/github.com/limetext/lime/backend/editor.go:364 +0xdf
created by github.com/limetext/lime/backend.GetEditor
	/home/pelle/go/src/github.com/limetext/lime/backend/editor.go:142 +0x737

goroutine 10 [select]:
github.com/limetext/lime/backend/watch.(*Watcher).Observe(0xc208038230)
	/home/pelle/go/src/github.com/limetext/lime/backend/watch/watch.go:199 +0x2ab
created by github.com/limetext/lime/backend.GetEditor
	/home/pelle/go/src/github.com/limetext/lime/backend/editor.go:143 +0x757

goroutine 11 [chan receive]:
github.com/limetext/log4go.ConsoleLogWriter.run(0xc20802a120, 0x7f3de1e6eb98, 0xc208034050)
	/home/pelle/go/src/github.com/limetext/log4go/termlog.go:27 +0x7a
created by github.com/limetext/log4go.NewConsoleLogWriter
	/home/pelle/go/src/github.com/limetext/log4go/termlog.go:19 +0x6b

goroutine 12 [chan receive]:
main.(*qmlfrontend).qmlBatchLoop(0xc20803a8a0)
	/home/pelle/go/src/github.com/limetext/lime/frontend/qml/main.go:444 +0x30a
created by main.main
	/home/pelle/go/src/github.com/limetext/lime/frontend/qml/main.go:856 +0x13d

goroutine 13 [chan receive]:
gopkg.in/qml%2ev1.RunMain(0xc2080d9e00)
	/home/pelle/go/src/gopkg.in/qml.v1/bridge.go:88 +0xd6
gopkg.in/qml%2ev1.(*Common).CreateWindow(0xc20800ac40, 0x0, 0x4aa300)
	/home/pelle/go/src/gopkg.in/qml.v1/qml.go:751 +0x19d
main.(*frontendWindow).launch(0xc2081c3020, 0xc20814e640, 0x7f3de1e7ed40, 0xc20800ac40)
	/home/pelle/go/src/github.com/limetext/lime/frontend/qml/main.go:288 +0x90
main.func·006(0xc20802a5a0)
	/home/pelle/go/src/github.com/limetext/lime/frontend/qml/main.go:699 +0x101
github.com/limetext/lime/backend.(*WindowEvent).Call(0xc143d0, 0xc20802a5a0)
	/home/pelle/go/src/github.com/limetext/lime/backend/events.go:96 +0x236
github.com/limetext/lime/backend.(*Editor).NewWindow(0xc2080018c0, 0xc208178c40)
	/home/pelle/go/src/github.com/limetext/lime/backend/editor.go:256 +0x27e
main.(*qmlfrontend).loop(0xc20803a8a0, 0x0, 0x0)
	/home/pelle/go/src/github.com/limetext/lime/frontend/qml/main.go:714 +0xb9a
main.*qmlfrontend.(main.loop)·fm(0x0, 0x0)
	/home/pelle/go/src/github.com/limetext/lime/frontend/qml/main.go:857 +0x39
gopkg.in/qml%2ev1.func·002()
	/home/pelle/go/src/gopkg.in/qml.v1/bridge.go:60 +0x49
created by gopkg.in/qml%2ev1.Run
	/home/pelle/go/src/gopkg.in/qml.v1/bridge.go:62 +0x1fd

goroutine 98 [select]:
github.com/limetext/lime/backend/watch.(*Watcher).Observe(0xc208039180)
	/home/pelle/go/src/github.com/limetext/lime/backend/watch/watch.go:199 +0x2ab
created by github.com/limetext/lime/backend/sublime.Init
	/home/pelle/go/src/github.com/limetext/lime/backend/sublime/sublime_manual.go:266 +0x32f

goroutine 16 [syscall]:
syscall.Syscall(0x0, 0x15, 0xc20821beb8, 0x10000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x15, 0xc20821beb8, 0x10000, 0x10000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0x15, 0xc20821beb8, 0x10000, 0x10000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/syscall/syscall_unix.go:136 +0x58
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc20802ca80)
	/home/pelle/go/src/gopkg.in/fsnotify.v1/inotify.go:144 +0x12b
created by gopkg.in/fsnotify%2ev1.NewWatcher
	/home/pelle/go/src/gopkg.in/fsnotify.v1/inotify.go:47 +0x37c
exit status 2
```

From what I can see qo-qml is working fine, maybe this is in the back-end as that python stacktrace could indicate

**Comment by pjoe** [comment]
Running: go test github.com/limetext/lime/backend/...

Everything passes

**Comment by pjoe** [comment]
Just tried running termbox frontend ... also seems to work.

**Comment by sonicflare** [comment]
Same error with Qt 5.3

**Comment by zidoms** [comment]
Seems this problem is due to 33cd650a119db09dc9bd98744ffb111b944f3743

**Comment by pjoe** [comment]
Maybe some issue with mapping 'complex' embedded types to qml?

I made this workaround:
```diff
diff --git a/backend/view.go b/backend/view.go
index 7827aa7..8d0fd66 100644
--- a/backend/view.go
+++ b/backend/view.go
@@ -31,7 +31,7 @@ type (
        View struct {
                HasSettings
                HasId
-               status
+               status      status
                name        string
                window      *Window
                buffer      Buffer
@@ -976,3 +976,15 @@ func (s status) GetStatus(key string) string {
 func (s status) EraseStatus(key string) {
        delete(s, key)
 }
+
+func (v *View) SetStatus(key string, val string) {
+       v.status[key] = val
+}
+
+func (v *View) GetStatus(key string) string {
+       return v.status[key]
+}
+
+func (v *View) EraseStatus(key string) {
+       delete(v.status, key)
+}

```

**Comment by zidoms** [comment]
Merged status type to view type for now as probably we won't use status anywhere else bc00df87d7c57582a4ae49a1ba3bb24bd22a3b6d. 
BTW this is [go-qml](https://github.com/go-qml/qml) issue and might happen again.
