### ISSUE TITLE
crash when opening file on OSX

### ISSUE THREAD

**Issue by bawigga** [limetext/lime#519]
```
2015/03/06 23:54:08 OpenDialog.qml:23: Choosed: /Users/brianwigginton/go/src/github.com/limetext/lime/frontend/qml/main.qml
[03/06/15 23:54:08] [INFO] Python sez: Exception ignored in: <module 'threading' from '/usr/local/Frameworks/Python.framework/Versions/3.4/lib/python3.4/threading.py'>
[03/06/15 23:54:08] [INFO] Python sez: Traceback (most recent call last):
[03/06/15 23:54:08] [INFO] Python sez:   File "/usr/local/Frameworks/Python.framework/Versions/3.4/lib/python3.4/threading.py", line 1290, in _shutdown
[03/06/15 23:54:08] [INFO] Python sez:     assert tlock.locked()
[03/06/15 23:54:08] [INFO] Python sez: AssertionError:
[03/06/15 23:54:08] [INFO] Python sez:
[03/06/15 23:54:08] [INFO] Python sez:
[03/06/15 23:54:08] [INFO] Python sez:
panic: unsupported variant type: 1024 (QJSValue)

goroutine 1 [running, locked to thread]:
gopkg.in/qml%2ev1.hookPanic(0x150cb800)
	/Users/brianwigginton/go/src/gopkg.in/qml.v1/bridge.go:631 +0x8d
gopkg.in/qml%2ev1._Cfunc_applicationExec()
	/Users/brianwigginton/go/src/gopkg.in/qml.v1/:59 +0x45
gopkg.in/qml%2ev1.Run(0xc2080d8b10, 0x0, 0x0)
	/Users/brianwigginton/go/src/gopkg.in/qml.v1/bridge.go:63 +0x204
main.main()
	/Users/brianwigginton/go/src/github.com/limetext/lime/frontend/qml/main.go:41 +0x192

goroutine 6 [chan receive]:
github.com/limetext/text.(*SerializedBuffer).worker(0xc20806a008)
	/Users/brianwigginton/go/src/github.com/limetext/text/serialized_buffer.go:40 +0x61
created by github.com/limetext/text.(*SerializedBuffer).init
	/Users/brianwigginton/go/src/github.com/limetext/text/serialized_buffer.go:26 +0xd9

goroutine 7 [syscall]:
syscall.Syscall6(0x16b, 0x3, 0x0, 0x0, 0xc20801d690, 0xa, 0x45e3170, 0x4063001, 0xc20805a3dc, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/asm_darwin_amd64.s:44 +0x5
syscall.kevent(0x3, 0x0, 0x0, 0xc20801d690, 0xa, 0x45e3170, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_darwin_amd64.go:200 +0x81
syscall.Kevent(0x3, 0x0, 0x0, 0x0, 0xc20801d690, 0xa, 0xa, 0x45e3170, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/syscall_bsd.go:480 +0x9b
gopkg.in/fsnotify%2ev1.read(0x3, 0xc20801d690, 0xa, 0xa, 0x45e3170, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/brianwigginton/go/src/gopkg.in/fsnotify.v1/kqueue.go:453 +0xab
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc20805a420)
	/Users/brianwigginton/go/src/gopkg.in/fsnotify.v1/kqueue.go:262 +0x1a2
created by gopkg.in/fsnotify%2ev1.NewWatcher
	/Users/brianwigginton/go/src/gopkg.in/fsnotify.v1/kqueue.go:61 +0x31f

goroutine 8 [chan send]:
gopkg.in/qml%2ev1.RunMain(0xc2082e6480)
	/Users/brianwigginton/go/src/gopkg.in/qml.v1/bridge.go:85 +0xb1
gopkg.in/qml%2ev1.(*Common).Call(0xc20817c280, 0x4407ad0, 0xa, 0xc20832c670, 0x1, 0x1, 0x0, 0x0)
	/Users/brianwigginton/go/src/gopkg.in/qml.v1/qml.go:705 +0x2c9
main.(*frontendView).bufferChanged(0xc208130b40, 0x66bdbc8, 0xc20806a000, 0x1de3, 0xf4)
	/Users/brianwigginton/go/src/github.com/limetext/lime/frontend/qml/frontend_view.go:96 +0x5fa
main.(*frontendView).Inserted(0xc208130b40, 0x66bdbc8, 0xc20806a000, 0x1de3, 0x1ed7, 0xc208288800, 0xf4, 0x100)
	/Users/brianwigginton/go/src/github.com/limetext/lime/frontend/qml/frontend_view.go:111 +0x53
github.com/limetext/text.(*buffer).InsertR(0xc20806a000, 0x1de3, 0xc208288800, 0xf4, 0x100, 0x0, 0x0)
	/Users/brianwigginton/go/src/github.com/limetext/text/buffer.go:264 +0x2d9
github.com/limetext/text.(*buffer).Insert(0xc20806a000, 0x1de3, 0xc2081f6300, 0xf4, 0x0, 0x0)
	/Users/brianwigginton/go/src/github.com/limetext/text/buffer.go:273 +0xb2
github.com/limetext/text.(*insertAction).Apply(0xc208294bd0)
	/Users/brianwigginton/go/src/github.com/limetext/text/action.go:72 +0x82
github.com/limetext/text.(*CompositeAction).AddExec(0xc208290008, 0x66c5000, 0xc208294bd0)
	/Users/brianwigginton/go/src/github.com/limetext/text/action.go:64 +0x1b5
github.com/limetext/lime/backend.(*View).Insert(0xc20807e100, 0xc208290000, 0x1de3, 0xc2081f6200, 0xf4, 0xc2081f6200)
	/Users/brianwigginton/go/src/github.com/limetext/lime/backend/view.go:381 +0x5a9
github.com/limetext/lime/backend.(*Editor).handleLog(0xc208000d80, 0xc208448000, 0xe7)
	/Users/brianwigginton/go/src/github.com/limetext/lime/backend/editor.go:428 +0x2c4
github.com/limetext/lime/backend.*Editor.(github.com/limetext/lime/backend.handleLog)·fm(0xc208448000, 0xe7)
	/Users/brianwigginton/go/src/github.com/limetext/lime/backend/editor.go:141 +0x3b
github.com/limetext/lime/backend/log.(*logWriter).handle(0xc20803ab40)
	/Users/brianwigginton/go/src/github.com/limetext/lime/backend/log/logwriter.go:37 +0x95
created by github.com/limetext/lime/backend/log.NewLogWriter
	/Users/brianwigginton/go/src/github.com/limetext/lime/backend/log/logwriter.go:31 +0xcb

goroutine 9 [chan receive]:
github.com/limetext/lime/backend.(*Editor).inputthread(0xc208000d80)
	/Users/brianwigginton/go/src/github.com/limetext/lime/backend/editor.go:364 +0x10f
created by github.com/limetext/lime/backend.GetEditor
	/Users/brianwigginton/go/src/github.com/limetext/lime/backend/editor.go:142 +0x737

goroutine 10 [select]:
github.com/limetext/lime/backend/watch.(*Watcher).Observe(0xc20802a1e0)
	/Users/brianwigginton/go/src/github.com/limetext/lime/backend/watch/watch.go:199 +0x2ab
created by github.com/limetext/lime/backend.GetEditor
	/Users/brianwigginton/go/src/github.com/limetext/lime/backend/editor.go:143 +0x757

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [chan receive]:
github.com/limetext/log4go.ConsoleLogWriter.run(0xc20805a900, 0x66bdad8, 0xc208038050)
	/Users/brianwigginton/go/src/github.com/limetext/log4go/termlog.go:27 +0x7a
created by github.com/limetext/log4go.NewConsoleLogWriter
	/Users/brianwigginton/go/src/github.com/limetext/log4go/termlog.go:19 +0x6b

goroutine 12 [chan receive]:
main.(*qmlfrontend).qmlBatchLoop(0xc20803b380)
	/Users/brianwigginton/go/src/github.com/limetext/lime/frontend/qml/qml_frontend.go:119 +0x30a
created by main.main
	/Users/brianwigginton/go/src/github.com/limetext/lime/frontend/qml/main.go:40 +0x13d

goroutine 13 [semacquire]:
sync.(*WaitGroup).Wait(0xc20812c780)
	/usr/local/Cellar/go/1.4.2/libexec/src/sync/waitgroup.go:132 +0x169
main.(*qmlfrontend).loop(0xc20803b380, 0x0, 0x0)
	/Users/brianwigginton/go/src/github.com/limetext/lime/frontend/qml/qml_frontend.go:381 +0x10b6
main.*qmlfrontend.(main.loop)·fm(0x0, 0x0)
	/Users/brianwigginton/go/src/github.com/limetext/lime/frontend/qml/main.go:41 +0x39
gopkg.in/qml%2ev1.func·002()
	/Users/brianwigginton/go/src/gopkg.in/qml.v1/bridge.go:60 +0x49
created by gopkg.in/qml%2ev1.Run
	/Users/brianwigginton/go/src/gopkg.in/qml.v1/bridge.go:62 +0x1fd

goroutine 54 [select]:
github.com/limetext/lime/backend/watch.(*Watcher).Observe(0xc2080da000)
	/Users/brianwigginton/go/src/github.com/limetext/lime/backend/watch/watch.go:199 +0x2ab
created by github.com/limetext/lime/backend/sublime.Init
	/Users/brianwigginton/go/src/github.com/limetext/lime/backend/sublime/sublime_manual.go:266 +0x32f

goroutine 52 [syscall]:
syscall.Syscall6(0x16b, 0x1b, 0x0, 0x0, 0xc20810c690, 0xa, 0x45e3170, 0x4063001, 0xc20805a61c, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/asm_darwin_amd64.s:44 +0x5
syscall.kevent(0x1b, 0x0, 0x0, 0xc20810c690, 0xa, 0x45e3170, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_darwin_amd64.go:200 +0x81
syscall.Kevent(0x1b, 0x0, 0x0, 0x0, 0xc20810c690, 0xa, 0xa, 0x45e3170, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/syscall_bsd.go:480 +0x9b
gopkg.in/fsnotify%2ev1.read(0x1b, 0xc20810c690, 0xa, 0xa, 0x45e3170, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/brianwigginton/go/src/gopkg.in/fsnotify.v1/kqueue.go:453 +0xab
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc20805a660)
	/Users/brianwigginton/go/src/gopkg.in/fsnotify.v1/kqueue.go:262 +0x1a2
created by gopkg.in/fsnotify%2ev1.NewWatcher
	/Users/brianwigginton/go/src/gopkg.in/fsnotify.v1/kqueue.go:61 +0x31f

goroutine 38 [chan receive]:
main.func·009()
	/Users/brianwigginton/go/src/github.com/limetext/lime/frontend/qml/qml_frontend.go:365 +0x7d
created by main.(*qmlfrontend).loop
	/Users/brianwigginton/go/src/github.com/limetext/lime/frontend/qml/qml_frontend.go:372 +0x1029

goroutine 68 [semacquire]:
sync.(*Mutex).Lock(0xc2080d82a0)
	/usr/local/Cellar/go/1.4.2/libexec/src/sync/mutex.go:66 +0xd3
gopkg.in/qml%2ev1.(*Window).Wait(0xc208126040)
	/Users/brianwigginton/go/src/gopkg.in/qml.v1/qml.go:911 +0xe2
main.func·001()
	/Users/brianwigginton/go/src/github.com/limetext/lime/frontend/qml/frontend_window.go:30 +0x37
created by main.(*frontendWindow).launch
	/Users/brianwigginton/go/src/github.com/limetext/lime/frontend/qml/frontend_window.go:32 +0x195

goroutine 69 [chan receive]:
github.com/limetext/lime/backend.(*View).parsethread(0xc2080d2000)
	/Users/brianwigginton/go/src/github.com/limetext/lime/backend/view.go:216 +0x158
created by github.com/limetext/lime/backend.newView
	/Users/brianwigginton/go/src/github.com/limetext/lime/backend/view.go:75 +0x23d

goroutine 70 [chan receive]:
github.com/limetext/text.(*SerializedBuffer).worker(0xc208122088)
	/Users/brianwigginton/go/src/github.com/limetext/text/serialized_buffer.go:40 +0x61
created by github.com/limetext/text.(*SerializedBuffer).init
	/Users/brianwigginton/go/src/github.com/limetext/text/serialized_buffer.go:26 +0xd9

goroutine 76 [chan receive]:
github.com/limetext/lime/backend.(*View).parsethread(0xc2080d2200)
	/Users/brianwigginton/go/src/github.com/limetext/lime/backend/view.go:216 +0x158
created by github.com/limetext/lime/backend.newView
	/Users/brianwigginton/go/src/github.com/limetext/lime/backend/view.go:75 +0x23d

goroutine 77 [chan receive]:
github.com/limetext/text.(*SerializedBuffer).worker(0xc20806a708)
	/Users/brianwigginton/go/src/github.com/limetext/text/serialized_buffer.go:40 +0x61
created by github.com/limetext/text.(*SerializedBuffer).init
	/Users/brianwigginton/go/src/github.com/limetext/text/serialized_buffer.go:26 +0xd9

goroutine 56 [syscall]:
syscall.Syscall6(0x16b, 0x59, 0x0, 0x0, 0xc208108690, 0xa, 0xc208108538, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/asm_darwin_amd64.s:44 +0x5
syscall.kevent(0x59, 0x0, 0x0, 0xc208108690, 0xa, 0xc208108538, 0xc208108517, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_darwin_amd64.go:200 +0x81
syscall.Kevent(0x59, 0x0, 0x0, 0x0, 0xc208108690, 0xa, 0xa, 0xc208108538, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/syscall_bsd.go:480 +0x9b
gopkg.in/fsnotify%2ev0.(*Watcher).readEvents(0xc208064140)
	/Users/brianwigginton/go/src/gopkg.in/fsnotify.v0/fsnotify_bsd.go:329 +0x43c
created by gopkg.in/fsnotify%2ev0.NewWatcher
	/Users/brianwigginton/go/src/gopkg.in/fsnotify.v0/fsnotify_bsd.go:105 +0x56a

goroutine 57 [chan receive]:
gopkg.in/fsnotify%2ev0.(*Watcher).purgeEvents(0xc208064140)
	/Users/brianwigginton/go/src/gopkg.in/fsnotify.v0/fsnotify.go:21 +0x58
created by gopkg.in/fsnotify%2ev0.NewWatcher
	/Users/brianwigginton/go/src/gopkg.in/fsnotify.v0/fsnotify_bsd.go:106 +0x584

```

**Comment by bawigga** [comment]
Looks like this was solved upstream, but is still pending a merge https://github.com/go-qml/qml/pull/140

**Comment by zoli** [comment]
Isn't this dup of #478?

**Comment by quarnster** [comment]
closing as dup of #478

**Comment by bawigga** [comment]
ah yip, sorry i missed that issue.
