### ISSUE TITLE
Problem on Debian jessie/sid

### ISSUE THREAD

**Issue by sasanrose** [limetext/lime#534]
Hi,

I have built lime with qml frontend. Although, I installed qml quick modules needed by lime, I still have a broken frontend. Cpu usage is high and almost all the functionalities are broken. Here are some information and debug log:
```bash
$ cat /etc/debian_version
jessie/sid
$ go version
go version go1.4.2 linux/amd64
$ ./qml
[04/12/15 11:59:56] [DEBG] calling newEngine
[04/12/15 11:59:56] [INFO] Initializing
[04/12/15 11:59:56] [INFO] Loaded ../../packages/Default/Default.sublime-keymap
[04/12/15 11:59:56] [INFO] Loaded ../../packages/Default/Default (Linux).sublime-keymap
[04/12/15 11:59:56] [INFO] Loaded ../../packages/User/Default.sublime-keymap
[04/12/15 11:59:56] [INFO] Loaded ../../packages/User/Default (Linux).sublime-keymap
[04/12/15 11:59:56] [DEBG] ../../packages/User is watched already
[04/12/15 11:59:56] [INFO] Loaded ../../packages/Default/Preferences.sublime-settings
[04/12/15 11:59:56] [INFO] Loaded ../../packages/Default/Preferences (Linux).sublime-settings
[04/12/15 11:59:56] [INFO] Loaded ../../packages/User/Preferences.sublime-settings
[04/12/15 11:59:56] [DEBG] ../../packages/User is watched already
[04/12/15 11:59:56] [DEBG] OnInit callbacks executing
[04/12/15 11:59:56] [DEBG] setvar frontend
[04/12/15 11:59:56] [DEBG] setvar editor
[04/12/15 11:59:56] [DEBG] loadfile
[04/12/15 11:59:57] [INFO] Reloading plugin ../../packages/Vintageous
[04/12/15 11:59:57] [INFO] Python sez: Loading plugin Vintageous.action_cmds
[04/12/15 11:59:57] [INFO] Python sez: Loading plugin Vintageous.jump_list_cmds
[04/12/15 11:59:57] [INFO] Python sez: Loading plugin Vintageous.motion_cmds
[04/12/15 11:59:57] [INFO] Python sez: Skipping registering irreversible_text: irreversible_text is already a registered command
[04/12/15 11:59:57] [INFO] Python sez: Loading plugin Vintageous.run
[04/12/15 11:59:57] [INFO] Python sez: Loading plugin Vintageous.state
[04/12/15 11:59:57] [INFO] Python sez: Skipping registering irreversible_text: irreversible_text is already a registered command
[04/12/15 11:59:57] [INFO] Python sez: Traceback (most recent call last):
[04/12/15 11:59:57] [INFO] Python sez:   File "../../backend/sublime/sublime_plugin.py", line 133, in reload_plugin
    module.plugin_loaded()
[04/12/15 11:59:57] [INFO] Python sez:   File "../../packages/Vintageous/state.py", line 75, in plugin_loaded
    view = sublime.active_window().active_view()
[04/12/15 11:59:57] [INFO] Python sez: AttributeError: 'NoneType' object has no attribute 'active_view'
[04/12/15 11:59:57] [INFO] Python sez: Loading plugin Vintageous.test_runner
[04/12/15 11:59:57] [INFO] Python sez: Loading plugin Vintageous.transformers
[04/12/15 11:59:57] [INFO] Python sez: Loading plugin Vintageous.transformers_visual
2015/04/12 11:59:57 LimeView.qml:44: file:////home/sasan/gocode/src/github.com/limetext/lime/frontend/qml/LimeView.qml:44:5: QML ListView: Cannot set a negative cache buffer
2015/04/12 11:59:57 LimeView.qml:44: file:////home/sasan/gocode/src/github.com/limetext/lime/frontend/qml/LimeView.qml:44:5: QML ListView: Cannot set a negative cache buffer
2015/04/12 11:59:57 LimeView.qml:44: file:////home/sasan/gocode/src/github.com/limetext/lime/frontend/qml/LimeView.qml:44:5: QML ListView: Cannot set a negative cache buffer
2015/04/12 11:59:57 LimeView.qml:44: file:////home/sasan/gocode/src/github.com/limetext/lime/frontend/qml/LimeView.qml:44:5: QML ListView: Binding loop detected for property "cacheBuffer"
2015/04/12 11:59:57 main.qml.:19: file:////home/sasan/gocode/src/github.com/limetext/lime/frontend/qml/main.qml.:19: TypeError: Cannot read property 'item' of undefined
2015/04/12 11:59:57 main.qml.:295: file:////home/sasan/gocode/src/github.com/limetext/lime/frontend/qml/main.qml.:295: TypeError: Cannot read property 'visibleArea' of undefined
2015/04/12 11:59:57 main.qml.:295: file:////home/sasan/gocode/src/github.com/limetext/lime/frontend/qml/main.qml.:295: TypeError: Cannot read property 'visibleArea' of undefined
2015/04/12 11:59:57 main.qml.:295: file:////home/sasan/gocode/src/github.com/limetext/lime/frontend/qml/main.qml.:295: TypeError: Cannot read property 'visibleArea' of undefined
2015/04/12 11:59:57 LimeView.qml.:44: file:////home/sasan/gocode/src/github.com/limetext/lime/frontend/qml/LimeView.qml.:44:5: QML ListView: Cannot set a negative cache buffer
2015/04/12 11:59:57 LimeView.qml.:44: file:////home/sasan/gocode/src/github.com/limetext/lime/frontend/qml/LimeView.qml.:44:5: QML ListView: Cannot set a negative cache buffer
2015/04/12 11:59:57 main.qml.:295: file:////home/sasan/gocode/src/github.com/limetext/lime/frontend/qml/main.qml.:295: TypeError: Cannot read property 'visibleArea' of undefined
2015/04/12 11:59:57 main.qml.:295: file:////home/sasan/gocode/src/github.com/limetext/lime/frontend/qml/main.qml.:295: TypeError: Cannot read property 'visibleArea' of undefined
[04/12/15 11:59:57] [INFO] Loaded ../../packages/Vintageous/Default.sublime-keymap
[04/12/15 11:59:57] [INFO] Loaded ../../packages/Vintageous/Default (Linux).sublime-keymap
[04/12/15 11:59:57] [DEBG] ../../packages/Vintageous is watched already
[04/12/15 11:59:57] [INFO] Loaded ../../packages/Vintageous/Preferences.sublime-settings
[04/12/15 11:59:57] [DEBG] ../../packages/Vintageous is watched already
[04/12/15 11:59:57] [INFO] Loaded ../../packages/Vintageous/Preferences (Linux).sublime-settings
[04/12/15 11:59:57] [DEBG] ../../packages/Vintageous is watched already
[04/12/15 11:59:57] [INFO] Loaded ../../packages/User/Preferences.sublime-settings
[04/12/15 11:59:57] [DEBG] OnInit callbacks finished
[04/12/15 11:59:57] [INFO] Loaded ../../packages/Go/Go.sublime-settings
[04/12/15 11:59:57] [WARN] Couldn't watch ../../packages/Go/Go.sublime-settings: The callback argument does satisfy any File*Callback interfaces
[04/12/15 11:59:57] [INFO] Loaded ../../packages/User/Go.sublime-settings
[04/12/15 11:59:57] [DEBG] ../../packages/User is watched already
2015/04/12 11:59:57 LimeView.qml.:44: file:////home/sasan/gocode/src/github.com/limetext/lime/frontend/qml/LimeView.qml.:44:5: QML ListView: Cannot set a negative cache buffer
2015/04/12 11:59:57 LimeView.qml.:44: file:////home/sasan/gocode/src/github.com/limetext/lime/frontend/qml/LimeView.qml.:44:5: QML ListView: Cannot set a negative cache buffer
[04/12/15 11:59:59] [INFO] Loaded ../../packages/Go/Go.sublime-settings
[04/12/15 11:59:59] [DEBG] ../../packages is watched already
[04/12/15 11:59:59] [WARN] Couldn't watch ../../packages/Go/Go.sublime-settings: The callback argument does satisfy any File*Callback interfaces
[04/12/15 11:59:59] [INFO] Loaded ../../packages/User/Go.sublime-settings
[04/12/15 11:59:59] [DEBG] ../../packages/User is watched already
[04/12/15 11:59:59] [DEBG] Waiting for all windows to close

```

**Comment by zoli** [comment]
The frontends aren't ready for users yet.
