### ISSUE TITLE
ROR

### ISSUE THREAD

**Issue by yurivict** [limetext/lime#559]
I followed your instruction how to build from source, and got errors:
```
ok      github.com/limetext/lime-backend/lib/render/textmate    0.004s
[12/13/15 16:05:21] [EROR] Failed to register command nop: Command wasn't registered in any list: nop
[12/13/15 16:05:21] [INFO] Initializing
[12/13/15 16:05:21] [INFO] Loaded ../packages/Default/Default.sublime-keymap
[12/13/15 16:05:21] [WARN] Couldn't watch ../packages/Default/Default.sublime-keymap: The callback argument does satisfy any File*Callback interfaces
[12/13/15 16:05:21] [INFO] Loaded ../packages/Default/Default (Linux).sublime-keymap
[12/13/15 16:05:21] [DEBG] ../packages is watched already
[12/13/15 16:05:21] [WARN] Couldn't watch ../packages/Default/Default (Linux).sublime-keymap: The callback argument does satisfy any File*Callback interfaces
[12/13/15 16:05:21] [INFO] Loaded ../packages/User/Default.sublime-keymap
[12/13/15 16:05:21] [DEBG] ../packages is watched already
[12/13/15 16:05:21] [WARN] Couldn't watch ../packages/User/Default.sublime-keymap: The callback argument does satisfy any File*Callback interfaces
[12/13/15 16:05:21] [INFO] Loaded ../packages/User/Default (Linux).sublime-keymap
[12/13/15 16:05:21] [DEBG] ../packages is watched already
[12/13/15 16:05:21] [WARN] Couldn't watch ../packages/User/Default (Linux).sublime-keymap: The callback argument does satisfy any File*Callback interfaces
[12/13/15 16:05:21] [INFO] Loaded ../packages/Default/Preferences.sublime-settings
[12/13/15 16:05:21] [DEBG] ../packages is watched already
[12/13/15 16:05:21] [WARN] Couldn't watch ../packages/Default/Preferences.sublime-settings: The callback argument does satisfy any File*Callback interfaces
[12/13/15 16:05:21] [INFO] Loaded ../packages/Default/Preferences (Linux).sublime-settings
[12/13/15 16:05:21] [DEBG] ../packages is watched already
[12/13/15 16:05:21] [WARN] Couldn't watch ../packages/Default/Preferences (Linux).sublime-settings: The callback argument does satisfy any File*Callback interfaces
[12/13/15 16:05:21] [INFO] Loaded ../packages/User/Preferences.sublime-settings
[12/13/15 16:05:21] [DEBG] ../packages is watched already
[12/13/15 16:05:21] [WARN] Couldn't watch ../packages/User/Preferences.sublime-settings: The callback argument does satisfy any File*Callback interfaces
[12/13/15 16:05:21] [DEBG] OnInit callbacks executing
[12/13/15 16:05:22] [INFO] Reloading plugin ../packages/Vintageous
[12/13/15 16:05:22] [EROR] Couldn't open dir: open ../packages/Vintageous: no such file or directory
[12/13/15 16:05:22] [INFO] Loaded ../packages/Vintageous/Default.sublime-keymap
[12/13/15 16:05:22] [DEBG] ../packages is watched already
[12/13/15 16:05:22] [WARN] Couldn't watch ../packages/Vintageous/Default.sublime-keymap: The callback argument does satisfy any File*Callback interfaces
[12/13/15 16:05:22] [INFO] Loaded ../packages/Vintageous/Default (Linux).sublime-keymap
[12/13/15 16:05:22] [DEBG] ../packages is watched already
[12/13/15 16:05:22] [WARN] Couldn't watch ../packages/Vintageous/Default (Linux).sublime-keymap: The callback argument does satisfy any File*Callback interfaces
[12/13/15 16:05:22] [INFO] Loaded ../packages/Vintageous/Preferences.sublime-settings
[12/13/15 16:05:22] [DEBG] ../packages is watched already
[12/13/15 16:05:22] [WARN] Couldn't watch ../packages/Vintageous/Preferences.sublime-settings: The callback argument does satisfy any File*Callback interfaces
[12/13/15 16:05:22] [INFO] Loaded ../packages/Vintageous/Preferences (Linux).sublime-settings
[12/13/15 16:05:22] [DEBG] ../packages is watched already
[12/13/15 16:05:22] [WARN] Couldn't watch ../packages/Vintageous/Preferences (Linux).sublime-settings: The callback argument does satisfy any File*Callback interfaces
[12/13/15 16:05:22] [INFO] Loaded ../packages/User/Preferences.sublime-settings
[12/13/15 16:05:22] [DEBG] ../packages is watched already
[12/13/15 16:05:22] [WARN] Couldn't watch ../packages/User/Preferences.sublime-settings: The callback argument does satisfy any File*Callback interfaces
[12/13/15 16:05:22] [DEBG] OnInit callbacks finished
[12/13/15 16:05:22] [INFO] Reloading plugin testdata/plugins
[12/13/15 16:05:22] [INFO] Python sez: Loading plugin plugins.test
[12/13/15 16:05:22] [INFO] Loaded testdata/plugins/Default.sublime-keymap
[12/13/15 16:05:22] [DEBG] testdata/plugins is watched already
[12/13/15 16:05:22] [INFO] Loaded testdata/plugins/Default (Linux).sublime-keymap
[12/13/15 16:05:22] [DEBG] testdata/plugins is watched already
[12/13/15 16:05:22] [INFO] Loaded testdata/plugins/Preferences.sublime-settings
[12/13/15 16:05:22] [DEBG] testdata/plugins is watched already
[12/13/15 16:05:22] [INFO] Loaded testdata/plugins/Preferences (Linux).sublime-settings
[12/13/15 16:05:22] [DEBG] testdata/plugins is watched already
[12/13/15 16:05:22] [INFO] Loaded ../packages/User/Preferences.sublime-settings
[12/13/15 16:05:22] [DEBG] ../packages is watched already
[12/13/15 16:05:22] [WARN] Couldn't watch ../packages/User/Preferences.sublime-settings: The callback argument does satisfy any File*Callback interfaces
[12/13/15 16:05:22] [DEBG] Running plugin_test.py
[12/13/15 16:05:22] [INFO] Python sez: new file
[12/13/15 16:05:22] [INFO] Python sez: running command
[12/13/15 16:05:22] [INFO] Python sez: my view's id is: 12
[12/13/15 16:05:22] [INFO] Python sez: command ran
[12/13/15 16:05:22] [INFO] Python sez: (0, 0)
[12/13/15 16:05:22] [DEBG] WindowCommand: map[]
[12/13/15 16:05:22] [INFO] Python sez: my window's id is 13
[12/13/15 16:05:22] [DEBG] Ran plugin_test.py
[12/13/15 16:05:22] [DEBG] Running region_test.py
[12/13/15 16:05:22] [DEBG] Ran region_test.py
[12/13/15 16:05:22] [DEBG] Running regionset_test.py
[12/13/15 16:05:22] [DEBG] Ran regionset_test.py
[12/13/15 16:05:22] [DEBG] Running reload_test.py
[12/13/15 16:05:22] [INFO] Python sez: Testing plugin reload
[12/13/15 16:05:22] [INFO] Python sez: new file
[12/13/15 16:05:22] [INFO] Python sez: running command
[12/13/15 16:05:22] [INFO] Python sez: command ran
[12/13/15 16:05:22] [INFO] Python sez: Traceback (most recent call last):
[12/13/15 16:05:22] [INFO] Python sez:   File "testdata/reload_test.py", line 10, in <module>
    assert v.substr(sublime.Region(0, v.size())) == "Tada"
[12/13/15 16:05:22] [INFO] Python sez: AssertionError
[12/13/15 16:05:22] [EROR] builtins.AssertionError: 
[12/13/15 16:05:22] [DEBG] Running stress_test.py
[12/13/15 16:05:27] [DEBG] Ran stress_test.py
[12/13/15 16:05:27] [DEBG] Running unittest_test.py
[12/13/15 16:05:27] [DEBG] Ran unittest_test.py
[12/13/15 16:05:27] [DEBG] Running view_test.py
[12/13/15 16:05:27] [DEBG] Ran view_test.py
[12/13/15 16:05:27] [DEBG] Running window command: vintage_ex_run_data_file_based_tests map[suite_name:state]
[12/13/15 16:05:27] [DEBG] No such window command: vintage_ex_run_data_file_based_tests
[12/13/15 16:05:27] [DEBG] Running window command: vintage_ex_run_data_file_based_tests map[suite_name:registers]
[12/13/15 16:05:27] [DEBG] No such window command: vintage_ex_run_data_file_based_tests
[12/13/15 16:05:27] [DEBG] Running window command: vintage_ex_run_data_file_based_tests map[suite_name:settings]
[12/13/15 16:05:27] [DEBG] No such window command: vintage_ex_run_data_file_based_tests
[12/13/15 16:05:27] [DEBG] Running window command: vintage_ex_run_data_file_based_tests map[suite_name:constants]
[12/13/15 16:05:27] [DEBG] No such window command: vintage_ex_run_data_file_based_tests
[12/13/15 16:05:27] [DEBG] Running window command: vintage_ex_run_data_file_based_tests map[suite_name:registers]
[12/13/15 16:05:27] [DEBG] No such window command: vintage_ex_run_data_file_based_tests
[12/13/15 16:05:27] [DEBG] Running window command: vintage_ex_run_data_file_based_tests map[suite_name:cmd_data]
[12/13/15 16:05:27] [DEBG] No such window command: vintage_ex_run_data_file_based_tests
[12/13/15 16:05:27] [DEBG] Running window command: vintage_ex_run_data_file_based_tests map[suite_name:marks]
[12/13/15 16:05:27] [DEBG] No such window command: vintage_ex_run_data_file_based_tests
--- FAIL: TestSublime (5.61s)
        sublime_test.go:36: 00006534 146 [2015/12/13 16:05:22 PST] [INFO] (github.com/limetext/lime-backend/lib/log.(*logger).Info:7) Loaded ../packages/User/Preferences.sublime-settings
        sublime_test.go:36: 00006693 125 [2015/12/13 16:05:22 PST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*logger).Debug:3) ../packages is watched already
        sublime_test.go:36: 00006831 220 [2015/12/13 16:05:22 PST] [WARN] (github.com/limetext/lime-backend/lib/log.(*logger).Warn:12) Couldn't watch ../packages/User/Preferences.sublime-settings: The callback argument does satisfy any File*Callback interfaces
        sublime_test.go:36: 00007064 120 [2015/12/13 16:05:22 PST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*logger).Debug:3) OnInit callbacks finished
        sublime_test.go:36: 00007197 127 [2015/12/13 16:05:22 PST] [INFO] (github.com/limetext/lime-backend/lib/log.(*logger).Info:7) Reloading plugin testdata/plugins
        sublime_test.go:36: 00007337 133 [2015/12/13 16:05:22 PST] [INFO] (github.com/limetext/lime-backend/lib/log.(*logger).Info:7) Python sez: Loading plugin plugins.test
        sublime_test.go:36: 00007483 140 [2015/12/13 16:05:22 PST] [INFO] (github.com/limetext/lime-backend/lib/log.(*logger).Info:7) Loaded testdata/plugins/Default.sublime-keymap
        sublime_test.go:36: 00007636 130 [2015/12/13 16:05:22 PST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*logger).Debug:3) testdata/plugins is watched already
        sublime_test.go:36: 00007779 148 [2015/12/13 16:05:22 PST] [INFO] (github.com/limetext/lime-backend/lib/log.(*logger).Info:7) Loaded testdata/plugins/Default (Linux).sublime-keymap
        sublime_test.go:36: 00007940 130 [2015/12/13 16:05:22 PST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*logger).Debug:3) testdata/plugins is watched already
        sublime_test.go:36: 00008083 146 [2015/12/13 16:05:22 PST] [INFO] (github.com/limetext/lime-backend/lib/log.(*logger).Info:7) Loaded testdata/plugins/Preferences.sublime-settings
        sublime_test.go:36: 00008242 130 [2015/12/13 16:05:22 PST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*logger).Debug:3) testdata/plugins is watched already
        sublime_test.go:36: 00008385 154 [2015/12/13 16:05:22 PST] [INFO] (github.com/limetext/lime-backend/lib/log.(*logger).Info:7) Loaded testdata/plugins/Preferences (Linux).sublime-settings
        sublime_test.go:36: 00008552 130 [2015/12/13 16:05:22 PST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*logger).Debug:3) testdata/plugins is watched already
        sublime_test.go:36: 00008695 146 [2015/12/13 16:05:22 PST] [INFO] (github.com/limetext/lime-backend/lib/log.(*logger).Info:7) Loaded ../packages/User/Preferences.sublime-settings
        sublime_test.go:36: 00008854 125 [2015/12/13 16:05:22 PST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*logger).Debug:3) ../packages is watched already
        sublime_test.go:36: 00008992 220 [2015/12/13 16:05:22 PST] [WARN] (github.com/limetext/lime-backend/lib/log.(*logger).Warn:12) Couldn't watch ../packages/User/Preferences.sublime-settings: The callback argument does satisfy any File*Callback interfaces
        sublime_test.go:36: 00009225 117 [2015/12/13 16:05:22 PST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*logger).Debug:3) Running plugin_test.py
        sublime_test.go:36: 00009355 114 [2015/12/13 16:05:22 PST] [INFO] (github.com/limetext/lime-backend/lib/log.(*logger).Info:7) Python sez: new file
        sublime_test.go:36: 00009482 121 [2015/12/13 16:05:22 PST] [INFO] (github.com/limetext/lime-backend/lib/log.(*logger).Info:7) Python sez: running command
        sublime_test.go:36: 00009616 125 [2015/12/13 16:05:22 PST] [INFO] (github.com/limetext/lime-backend/lib/log.(*logger).Info:7) Python sez: my view's id is: 12
        sublime_test.go:36: 00009754 117 [2015/12/13 16:05:22 PST] [INFO] (github.com/limetext/lime-backend/lib/log.(*logger).Info:7) Python sez: command ran
        sublime_test.go:36: 00009884 112 [2015/12/13 16:05:22 PST] [INFO] (github.com/limetext/lime-backend/lib/log.(*logger).Info:7) Python sez: (0, 0)
        sublime_test.go:36: 00010009 115 [2015/12/13 16:05:22 PST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*logger).Debug:3) WindowCommand: map[]
        sublime_test.go:36: 00010137 126 [2015/12/13 16:05:22 PST] [INFO] (github.com/limetext/lime-backend/lib/log.(*logger).Info:7) Python sez: my window's id is 13
        sublime_test.go:36: 00010276 113 [2015/12/13 16:05:22 PST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*logger).Debug:3) Ran plugin_test.py
        sublime_test.go:36: 00010402 117 [2015/12/13 16:05:22 PST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*logger).Debug:3) Running region_test.py
        sublime_test.go:36: 00010532 113 [2015/12/13 16:05:22 PST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*logger).Debug:3) Ran region_test.py
        sublime_test.go:36: 00010658 120 [2015/12/13 16:05:22 PST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*logger).Debug:3) Running regionset_test.py
        sublime_test.go:36: 00010791 116 [2015/12/13 16:05:22 PST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*logger).Debug:3) Ran regionset_test.py
        sublime_test.go:36: 00010920 117 [2015/12/13 16:05:22 PST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*logger).Debug:3) Running reload_test.py
        sublime_test.go:36: 00011050 127 [2015/12/13 16:05:22 PST] [INFO] (github.com/limetext/lime-backend/lib/log.(*logger).Info:7) Python sez: Testing plugin reload
        sublime_test.go:36: 00011190 114 [2015/12/13 16:05:22 PST] [INFO] (github.com/limetext/lime-backend/lib/log.(*logger).Info:7) Python sez: new file
        sublime_test.go:36: 00011317 121 [2015/12/13 16:05:22 PST] [INFO] (github.com/limetext/lime-backend/lib/log.(*logger).Info:7) Python sez: running command
        sublime_test.go:36: 00011451 117 [2015/12/13 16:05:22 PST] [INFO] (github.com/limetext/lime-backend/lib/log.(*logger).Info:7) Python sez: command ran
        sublime_test.go:36: 00011581 140 [2015/12/13 16:05:22 PST] [INFO] (github.com/limetext/lime-backend/lib/log.(*logger).Info:7) Python sez: Traceback (most recent call last):
        sublime_test.go:36: 00011734 219 [2015/12/13 16:05:22 PST] [INFO] (github.com/limetext/lime-backend/lib/log.(*logger).Info:7) Python sez:   File "testdata/reload_test.py", line 10, in <module>
                    assert v.substr(sublime.Region(0, v.size())) == "Tada"
        sublime_test.go:36: 00011966 120 [2015/12/13 16:05:22 PST] [INFO] (github.com/limetext/lime-backend/lib/log.(*logger).Info:7) Python sez: AssertionError
        sublime_test.go:104: builtins.AssertionError: 
        sublime_test.go:36: 00012099 120 [2015/12/13 16:05:22 PST] [EROR] (github.com/limetext/lime-backend/lib/log.(*logger).Error:4) builtins.AssertionError: 
        sublime_test.go:36: 00012232 117 [2015/12/13 16:05:22 PST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*logger).Debug:3) Running stress_test.py
        sublime_test.go:36: 00012362 113 [2015/12/13 16:05:27 PST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*logger).Debug:3) Ran stress_test.py
        sublime_test.go:36: 00012488 119 [2015/12/13 16:05:27 PST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*logger).Debug:3) Running unittest_test.py
        sublime_test.go:36: 00012620 115 [2015/12/13 16:05:27 PST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*logger).Debug:3) Ran unittest_test.py
        sublime_test.go:36: 00012748 115 [2015/12/13 16:05:27 PST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*logger).Debug:3) Running view_test.py
        sublime_test.go:36: 00012876 111 [2015/12/13 16:05:27 PST] [DEBG] (github.com/limetext/lime-backend/lib/log.(*logger).Debug:3) Ran view_test.py
FAIL
FAIL    github.com/limetext/lime-backend/lib/sublime    5.659s
```

**Comment by erbridge** [comment]
Which instructions did you follow? Tried these?

https://github.com/limetext/lime/wiki/Building

**Comment by yurivict** [comment]
Ok, it has built.

**Comment by erbridge** [comment]
If you could fix the instructions that didn't work for you, that would be great.
