### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by brunetto** [limetext/lime#566]
Hi!
I tried to create a Docker container for Lime following the instructions at https://github.com/limetext/lime/wiki/Building-on-Ubuntu-16.04. 
The Dockerfile can be found at https://github.com/brunetto/docker-lime/blob/master/Dockerfile. The environment is:

- go version go1.6.1 linux/amd64
- Ubuntu 16.04

The build step was successful but I was not able to run the binary because of the error:

`fatal error: unexpected signal during runtime execution` 

with a long trace.

I found sparse information about other people having similar errors but I didn't find a proper explanation or a solution. Is it possible that it depends on the latest Go version having problems with old C calls?

Thanks

**Comment by ricochet1k** [comment]
Post the stack traces please.

**Comment by brunetto** [comment]
```
[06/24/16 12:35:03] [INFO] Initializing
[06/24/16 12:35:03] [DEBG] OnInit callbacks executing
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x25 pc=0x7f701c4b3601]

runtime stack:
runtime.throw(0x923860, 0x2a)
	/usr/lib/go-1.6/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/lib/go-1.6/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 16 [syscall, locked to thread]:
runtime.cgocall(0x754b80, 0xc8200451b0, 0xc800000000)
	/usr/lib/go-1.6/src/runtime/cgocall.go:123 +0x11b fp=0xc820045178 sp=0xc820045148
github.com/limetext/gopy/lib._Cfunc_excName(0x7f701c83ed40, 0x0, 0x0)
	??:0 +0x40 fp=0xc8200451b0 sp=0xc820045178
github.com/limetext/gopy/lib.(*Error).Error(0xc820214180, 0x0, 0x0)
	/golang/src/github.com/limetext/gopy/lib/err.go:29 +0xbc fp=0xc8200452a8 sp=0xc8200451b0
fmt.(*pp).handleMethods(0xc82038a000, 0xc800000073, 0x0, 0xc800000001)
	/usr/lib/go-1.6/src/fmt/print.go:724 +0x4c2 fp=0xc820045388 sp=0xc8200452a8
fmt.(*pp).printArg(0xc82038a000, 0x83f320, 0xc820214180, 0x73, 0x0, 0x0)
	/usr/lib/go-1.6/src/fmt/print.go:806 +0x4a9 fp=0xc820045510 sp=0xc820045388
fmt.(*pp).doPrintf(0xc82038a000, 0x9046a0, 0x22, 0xc820388280, 0x1, 0x1)
	/usr/lib/go-1.6/src/fmt/print.go:1238 +0x1dcd fp=0xc820045898 sp=0xc820045510
fmt.Sprintf(0x9046a0, 0x22, 0xc820388280, 0x1, 0x1, 0x0, 0x0)
	/usr/lib/go-1.6/src/fmt/print.go:203 +0x6f fp=0xc8200458e8 sp=0xc820045898
github.com/limetext/log4go.Logger.Error(0xc820016600, 0x784100, 0xc820388290, 0xc820388280, 0x1, 0x1, 0x0, 0x0)
	/golang/src/github.com/limetext/log4go/log4go.go:451 +0x291 fp=0xc8200459f8 sp=0xc8200458e8
github.com/limetext/backend/log.(*logger).Error(0xc820028028, 0x784100, 0xc820388290, 0xc820388280, 0x1, 0x1, 0x0, 0x0)
	<autogenerated>:4 +0x7f fp=0xc820045a40 sp=0xc8200459f8
github.com/limetext/backend/log.Error(0x784100, 0xc820388290, 0xc820388280, 0x1, 0x1, 0x0, 0x0)
	/golang/src/github.com/limetext/backend/log/global.go:43 +0x69 fp=0xc820045a88 sp=0xc820045a40
github.com/limetext/sublime.onInit()
	/golang/src/github.com/limetext/sublime/package.go:244 +0x1ae fp=0xc820045b38 sp=0xc820045a88
github.com/limetext/backend.(*InitEvent).call(0xcda8b0)
	/golang/src/github.com/limetext/backend/events.go:79 +0x14a fp=0xc820045bb8 sp=0xc820045b38
github.com/limetext/backend.(*Editor).Init(0xc820001c80)
	/golang/src/github.com/limetext/backend/editor.go:185 +0xee fp=0xc820045c40 sp=0xc820045bb8
main.(*qmlfrontend).loop(0xc8202a1470, 0x0, 0x0)
	/golang/src/github.com/limetext/lime-qml/main/frontend.go:293 +0x60 fp=0xc820045f40 sp=0xc820045c40
main.(*qmlfrontend).(main.loop)-fm(0x0, 0x0)
	/golang/src/github.com/limetext/lime-qml/main/main.go:44 +0x2e fp=0xc820045f60 sp=0xc820045f40
github.com/limetext/qml-go.Run.func1(0xc82006bf80, 0xc820375570)
	/golang/src/github.com/limetext/qml-go/bridge.go:68 +0x2d fp=0xc820045f90 sp=0xc820045f60
runtime.goexit()
	/usr/lib/go-1.6/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820045f98 sp=0xc820045f90
created by github.com/limetext/qml-go.Run
	/golang/src/github.com/limetext/qml-go/bridge.go:70 +0x169

goroutine 1 [syscall, locked to thread]:
github.com/limetext/qml-go._Cfunc_applicationExec()
	??:0 +0x36
github.com/limetext/qml-go.Run(0xc820375570, 0x0, 0x0)
	/golang/src/github.com/limetext/qml-go/bridge.go:71 +0x16e
main.main()
	/golang/src/github.com/limetext/lime-qml/main/main.go:44 +0x20c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go-1.6/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [chan receive]:
github.com/limetext/log4go.ConsoleLogWriter.run(0xc82006a0c0, 0x7f7013f8b330, 0xc820028010)
	/golang/src/github.com/limetext/log4go/termlog.go:27 +0x81
created by github.com/limetext/log4go.NewConsoleLogWriter
	/golang/src/github.com/limetext/log4go/termlog.go:19 +0x6e

goroutine 6 [chan receive]:
github.com/limetext/log4go.ConsoleLogWriter.run(0xc82006a120, 0x7f7013f8b330, 0xc820028010)
	/golang/src/github.com/limetext/log4go/termlog.go:27 +0x81
created by github.com/limetext/log4go.NewConsoleLogWriter
	/golang/src/github.com/limetext/log4go/termlog.go:19 +0x6e

goroutine 7 [syscall]:
syscall.Syscall6(0xe8, 0x4, 0xc8200fdc24, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/syscall/asm_linux_amd64.s:44 +0x5
golang.org/x/sys/unix.EpollWait(0x4, 0xc8200fdc24, 0x7, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0)
	/golang/src/golang.org/x/sys/unix/zsyscall_linux_amd64.go:1220 +0x89
gopkg.in/fsnotify%2ev1.(*fdPoller).wait(0xc82000e540, 0x94fd00, 0x0, 0x0)
	/golang/src/gopkg.in/fsnotify.v1/inotify_poller.go:86 +0xbd
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc820012320)
	/golang/src/gopkg.in/fsnotify.v1/inotify.go:192 +0x1a8
created by gopkg.in/fsnotify%2ev1.NewWatcher
	/golang/src/gopkg.in/fsnotify.v1/inotify.go:61 +0x3e2

goroutine 8 [select]:
github.com/limetext/backend/watch.(*Watcher).Observe(0xc820012370)
	/golang/src/github.com/limetext/backend/watch/watcher.go:209 +0x2ef
created by github.com/limetext/backend/packages.init.1
	/golang/src/github.com/limetext/backend/packages/watcher.go:56 +0x175

goroutine 9 [chan receive]:
github.com/limetext/text.(*SerializedBuffer).worker(0xc8200ca088)
	/golang/src/github.com/limetext/text/serialized_buffer.go:40 +0x59
created by github.com/limetext/text.(*SerializedBuffer).init
	/golang/src/github.com/limetext/text/serialized_buffer.go:26 +0xcc

goroutine 10 [syscall]:
syscall.Syscall6(0xe8, 0x8, 0xc8201a9c24, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/syscall/asm_linux_amd64.s:44 +0x5
golang.org/x/sys/unix.EpollWait(0x8, 0xc8201a9c24, 0x7, 0x7, 0xffffffffffffffff, 0x0, 0x0, 0x0)
	/golang/src/golang.org/x/sys/unix/zsyscall_linux_amd64.go:1220 +0x89
gopkg.in/fsnotify%2ev1.(*fdPoller).wait(0xc82000e560, 0x94fd00, 0x0, 0x0)
	/golang/src/gopkg.in/fsnotify.v1/inotify_poller.go:86 +0xbd
gopkg.in/fsnotify%2ev1.(*Watcher).readEvents(0xc8200123c0)
	/golang/src/gopkg.in/fsnotify.v1/inotify.go:192 +0x1a8
created by gopkg.in/fsnotify%2ev1.NewWatcher
	/golang/src/gopkg.in/fsnotify.v1/inotify.go:61 +0x3e2

goroutine 11 [chan receive]:
github.com/limetext/backend/log.NewLogWriter.func1(0xc82000aad0, 0xc82000aac0)
	/golang/src/github.com/limetext/backend/log/logwriter.go:38 +0x51
created by github.com/limetext/backend/log.NewLogWriter
	/golang/src/github.com/limetext/backend/log/logwriter.go:41 +0xad

goroutine 12 [chan receive]:
github.com/limetext/backend.(*Editor).inputthread(0xc820001c80)
	/golang/src/github.com/limetext/backend/editor.go:376 +0xd3
created by github.com/limetext/backend.GetEditor
	/golang/src/github.com/limetext/backend/editor.go:159 +0x156a

goroutine 13 [select]:
github.com/limetext/backend/watch.(*Watcher).Observe(0xc820012410)
	/golang/src/github.com/limetext/backend/watch/watcher.go:209 +0x2ef
created by github.com/limetext/backend.GetEditor
	/golang/src/github.com/limetext/backend/editor.go:160 +0x1592

goroutine 14 [select]:
github.com/limetext/log4go.NewFileLogWriter.func1(0xc8200b2120)
	/golang/src/github.com/limetext/log4go/filelog.go:84 +0xab6
created by github.com/limetext/log4go.NewFileLogWriter
	/golang/src/github.com/limetext/log4go/filelog.go:116 +0x381

goroutine 15 [chan receive]:
main.(*qmlfrontend).qmlBatchLoop(0xc8202a1470)
	/golang/src/github.com/limetext/lime-qml/main/frontend.go:117 +0x407
created by main.main
	/golang/src/github.com/limetext/lime-qml/main/main.go:43 +0x1cb
```

**Comment by ricochet1k** [comment]
Hmm. gopy looks like it isn't too happy, and may need some work. What version of python are you using?

**Comment by brunetto** [comment]
```
# python --version
Python 2.7.11+
```

**Comment by zoli** [comment]
You need `Python 3.5` as stated in https://github.com/limetext/lime/wiki/Building.
